version: "3.8"

services:
    mailpit:
        image: axllent/mailpit:latest
        ports:
            - "1025:1025" # SMTP port
            - "8025:8025" # Web UI port
        environment:
            - MP_SMTP_AUTH_ACCEPT_ANY=1
            - MP_SMTP_AUTH_ALLOW_INSECURE=1
